import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.savedCollege.deleteMany();
  await prisma.college.deleteMany();
  await prisma.user.deleteMany();

  await prisma.college.createMany({
    data: [
      {
        name: "IIT Delhi",
        location: "Delhi",
        fees: 220000,
        rating: 4.8,
        placementRate: 92,
        courses: ["Computer Science", "Mechanical", "Electrical"],
        description: "Top IIT with strong research and excellent placements.",
        cutoffRank: 500,
        exam: "JEE",
      },
      {
        name: "IIT Bombay",
        location: "Maharashtra",
        fees: 225000,
        rating: 4.9,
        placementRate: 94,
        courses: ["Computer Science", "Aerospace", "Chemical"],
        description:
          "Premier IIT with outstanding academic reputation and placements.",
        cutoffRank: 300,
        exam: "JEE",
      },
      {
        name: "IIT Madras",
        location: "Tamil Nadu",
        fees: 215000,
        rating: 4.8,
        placementRate: 93,
        courses: ["Computer Science", "Civil", "Mechanical"],
        description: "Leading IIT known for innovation and strong outcomes.",
        cutoffRank: 400,
        exam: "JEE",
      },
      {
        name: "IIT Kanpur",
        location: "Uttar Pradesh",
        fees: 210000,
        rating: 4.7,
        placementRate: 91,
        courses: ["Computer Science", "Electrical", "Aerospace"],
        description: "Strong academic focus with high placement quality.",
        cutoffRank: 900,
        exam: "JEE",
      },
      {
        name: "IIT Kharagpur",
        location: "West Bengal",
        fees: 215000,
        rating: 4.7,
        placementRate: 90,
        courses: ["Computer Science", "Mining", "Mechanical"],
        description: "Oldest IIT with a large campus and diverse programs.",
        cutoffRank: 1200,
        exam: "JEE",
      },

      {
        name: "NIT Trichy",
        location: "Tamil Nadu",
        fees: 180000,
        rating: 4.6,
        placementRate: 88,
        courses: ["Computer Science", "Civil", "Production"],
        description: "Top NIT with balanced academics and placements.",
        cutoffRank: 7000,
        exam: "JEE",
      },
      {
        name: "NIT Surathkal",
        location: "Karnataka",
        fees: 175000,
        rating: 4.6,
        placementRate: 87,
        courses: ["Computer Science", "Mechanical", "Electronics"],
        description: "Strong placements and a good technical ecosystem.",
        cutoffRank: 7500,
        exam: "JEE",
      },
      {
        name: "NIT Warangal",
        location: "Telangana",
        fees: 170000,
        rating: 4.5,
        placementRate: 85,
        courses: ["Computer Science", "ECE", "Mechanical"],
        description: "Well-regarded NIT with strong tech outcomes.",
        cutoffRank: 8000,
        exam: "JEE",
      },

      {
        name: "BITS Pilani",
        location: "Rajasthan",
        fees: 550000,
        rating: 4.7,
        placementRate: 90,
        courses: ["Computer Science", "Electronics", "Biotechnology"],
        description:
          "Private institute known for flexibility and strong industry links.",
        cutoffRank: 3500,
        exam: "JEE",
      },
      {
        name: "BITS Goa",
        location: "Goa",
        fees: 545000,
        rating: 4.6,
        placementRate: 89,
        courses: ["Computer Science", "Mechanical", "Electronics"],
        description: "BITS campus with strong academics and good placements.",
        cutoffRank: 4500,
        exam: "JEE",
      },

      {
        name: "VIT Vellore",
        location: "Tamil Nadu",
        fees: 220000,
        rating: 4.3,
        placementRate: 80,
        courses: ["Computer Science", "Information Technology", "ECE"],
        description: "Large private university with broad course options.",
        cutoffRank: 25000,
        exam: "JEE",
      },
      {
        name: "VIT Chennai",
        location: "Tamil Nadu",
        fees: 210000,
        rating: 4.2,
        placementRate: 78,
        courses: ["Computer Science", "ECE", "AI"],
        description: "Growing campus with decent tech outcomes.",
        cutoffRank: 28000,
        exam: "JEE",
      },

      {
        name: "SRM Institute",
        location: "Tamil Nadu",
        fees: 250000,
        rating: 4.1,
        placementRate: 75,
        courses: ["Computer Science", "Data Science", "ECE"],
        description: "Industry-oriented programs with a large student base.",
        cutoffRank: 40000,
        exam: "JEE",
      },
      {
        name: "Manipal Institute of Technology",
        location: "Karnataka",
        fees: 430000,
        rating: 4.4,
        placementRate: 82,
        courses: ["Computer Science", "AI", "Mechanical"],
        description:
          "Well-known private institute with a strong alumni network.",
        cutoffRank: 18000,
        exam: "JEE",
      },

      {
        name: "DTU",
        location: "Delhi",
        fees: 160000,
        rating: 4.5,
        placementRate: 86,
        courses: ["Computer Science", "Mechanical", "Electrical"],
        description: "Top Delhi engineering college with strong ROI.",
        cutoffRank: 6000,
        exam: "JEE",
      },
      {
        name: "NSUT",
        location: "Delhi",
        fees: 155000,
        rating: 4.4,
        placementRate: 85,
        courses: ["Computer Science", "IT", "ECE"],
        description: "Competitive Delhi university with solid placements.",
        cutoffRank: 7000,
        exam: "JEE",
      },

      {
        name: "IIIT Hyderabad",
        location: "Telangana",
        fees: 450000,
        rating: 4.8,
        placementRate: 95,
        courses: ["Computer Science", "AI", "Electronics"],
        description:
          "Highly selective institute known for research and tech placements.",
        cutoffRank: 1000,
        exam: "JEE",
      },
      {
        name: "IIIT Bangalore",
        location: "Karnataka",
        fees: 400000,
        rating: 4.7,
        placementRate: 93,
        courses: ["Computer Science", "Data Science", "AI"],
        description:
          "Strong tech-focused institute with high placement outcomes.",
        cutoffRank: 2000,
        exam: "JEE",
      },

      {
        name: "Amity University",
        location: "Uttar Pradesh",
        fees: 300000,
        rating: 4.0,
        placementRate: 70,
        courses: ["Computer Science", "MBA", "Law"],
        description:
          "Private university with large campus and diverse courses.",
        cutoffRank: 50000,
        exam: "JEE",
      },
      {
        name: "Lovely Professional University",
        location: "Punjab",
        fees: 180000,
        rating: 3.9,
        placementRate: 68,
        courses: ["Computer Science", "Management", "Mechanical"],
        description: "Large private university with many program options.",
        cutoffRank: 60000,
        exam: "JEE",
      },

      {
        name: "Chandigarh University",
        location: "Punjab",
        fees: 170000,
        rating: 4.1,
        placementRate: 75,
        courses: ["Computer Science", "Business", "ECE"],
        description: "Fast-growing private university with broad intake.",
        cutoffRank: 45000,
        exam: "JEE",
      },
      {
        name: "Thapar Institute",
        location: "Punjab",
        fees: 420000,
        rating: 4.5,
        placementRate: 87,
        courses: ["Computer Science", "Mechanical", "Electronics"],
        description:
          "Established private engineering institute with strong reputation.",
        cutoffRank: 9000,
        exam: "JEE",
      },

      {
        name: "PES University",
        location: "Karnataka",
        fees: 380000,
        rating: 4.4,
        placementRate: 85,
        courses: ["Computer Science", "AI", "ECE"],
        description: "Popular Bengaluru institute with decent placements.",
        cutoffRank: 15000,
        exam: "JEE",
      },
      {
        name: "RV College of Engineering",
        location: "Karnataka",
        fees: 200000,
        rating: 4.6,
        placementRate: 90,
        courses: ["Computer Science", "ECE", "Mechanical"],
        description: "Top Bengaluru engineering college with strong ROI.",
        cutoffRank: 5000,
        exam: "JEE",
      },

      {
        name: "Anna University",
        location: "Tamil Nadu",
        fees: 140000,
        rating: 4.3,
        placementRate: 80,
        courses: ["Computer Science", "Civil", "Mechanical"],
        description: "State university with solid engineering programs.",
        cutoffRank: 12000,
        exam: "JEE",
      },
      {
        name: "Jadavpur University",
        location: "West Bengal",
        fees: 120000,
        rating: 4.6,
        placementRate: 88,
        courses: ["Computer Science", "Mechanical", "Electrical"],
        description: "High-ROI public university with strong outcomes.",
        cutoffRank: 4000,
        exam: "JEE",
      },
      {
        name: "AIIMS Delhi",
        location: "Delhi",
        fees: 50000,
        rating: 4.9,
        placementRate: 95,
        courses: ["MBBS"],
        description: "Top medical institute in India",
        cutoffRank: 100,
        exam: "NEET",
      },
      {
        name: "JIPMER Puducherry",
        location: "Puducherry",
        fees: 60000,
        rating: 4.7,
        placementRate: 90,
        courses: ["MBBS"],
        description: "Premier medical college",
        cutoffRank: 300,
        exam: "NEET",
      },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
